wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.9
    start_time: 1669588576
    t:
      1:
      - 1
      4: 3.7.9
      5: 0.12.5
      8:
      - 5
