wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.9
    start_time: 1675440226
    t:
      1:
      - 1
      3:
      - 16
      4: 3.7.9
      5: 0.12.5
      8:
      - 5
augment:
  desc: null
  value: true
augment_type:
  desc: null
  value: base_augment
batch_size:
  desc: null
  value: 256
channel_num:
  desc: null
  value: 9
channel_size:
  desc: null
  value: 9
debug:
  desc: null
  value: false
debug_input:
  desc: null
  value: true
denoise_image:
  desc: null
  value: false
denoise_sort:
  desc: null
  value: false
epochs:
  desc: null
  value: 100
filter_flash:
  desc: null
  value: false
filter_noise:
  desc: null
  value: false
global_time:
  desc: null
  value: false
height:
  desc: null
  value: 224
inspect_channel:
  desc: null
  value: all
interpolate:
  desc: null
  value: null
kernel_size:
  desc: null
  value: 14
label_map:
  desc: null
  value: ./Datasets/Caltech101-NIN/mapping.txt
learning_rate:
  desc: null
  value: 0.0003
load_model:
  desc: null
  value: null
loader_type:
  desc: null
  value: est_aggregation_positive
mahalanobis:
  desc: null
  value: 0.0
max_trajectory_speed:
  desc: null
  value: 0.0
mode:
  desc: null
  value: train
model:
  desc: null
  value: ResNet34
momentum:
  desc: null
  value: 0.9
name:
  desc: null
  value: EST_positive
neglect_polarity:
  desc: null
  value: false
no_cuda:
  desc: null
  value: false
num_classes:
  desc: null
  value: 101
num_workers:
  desc: null
  value: 0
on_the_fly:
  desc: null
  value: false
optimizer:
  desc: null
  value: Adam
parallel:
  desc: null
  value: true
pin_memory:
  desc: null
  value: true
quantize_sort:
  desc: null
  value: null
quantized:
  desc: null
  value: true
reshape:
  desc: null
  value: true
reshape_method:
  desc: null
  value: no_sample
save_by:
  desc: null
  value: epoch
save_every:
  desc: null
  value: 1
save_root_dir:
  desc: null
  value: ./experiments/
seed:
  desc: null
  value: 1
slice_augment:
  desc: null
  value: false
slice_augment_width:
  desc: null
  value: 0
slice_end:
  desc: null
  value: 30000
slice_events:
  desc: null
  value: true
slice_length:
  desc: null
  value: 30000
slice_method:
  desc: null
  value: random
slice_start:
  desc: null
  value: 0
strict:
  desc: null
  value: true
temperature:
  desc: null
  value: 1
train_file:
  desc: null
  value: ./Datasets/Caltech101-NIN/train_list.txt
trim_class_count:
  desc: null
  value: null
use_image:
  desc: null
  value: false
val_file:
  desc: null
  value: ./Datasets/Caltech101-NIN/val_list.txt
weight_decay:
  desc: null
  value: 0.0001
width:
  desc: null
  value: 224
